{% set name = "fastpath" %}
{% set version = "1.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "e1b4f1434d8472e63a3d78041b8b78c2b488d7233f5cac1d4821d9cbc93b5b1e"

build:
  number: 0
  skip: True  # [py27]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv "

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:

test:
  imports:
    - fastpathz

about:
  home: "https://github.com/deprekate/fastpath"
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  summary: "Fastpath is a fast and lightweight tool for finding the shortest path in a weighted graph"
  doc_url: "https://github.com/deprekate/fastpath/blob/master/README.md"
  dev_url: "https://github.com/deprekate/fastpath"

extra:
  recipe-maintainers:
    - linsalrob
  identifiers:
    - doi:10.1093/bioinformatics
